const UserActionTypes = {
    FETCH_LOGIN_START: 'FETCH_LOGIN_START',
    FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
    FETCH_LOGIN_FAILURE: 'FETCH_LOGIN_FAILURE',

    FETCH_REGISTER_START: 'FETCH_REGISTER_START',
    FETCH_REGISTER_SUCCESS: 'FETCH_REGISTER_SUCCESS',
    FETCH_REGISTER_FAILURE: 'FETCH_REGISTER_FAILURE',

    LOGOUT: 'LOGOUT',

    CLEAR_SUCCESS_FAILURE:'CLEAR_SUCCESS_FAILURE',

    ADD_DISCUSSION:'ADD_DISCUSSION',

    ADD_ANSWER:'ADD_ANSWER'
}

export default UserActionTypes;